services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    deploy:
      resources:
        limits:
          memory: 1.5G
    mem_limit: 1.5g
    volumes:
      - "~/minecraft_data:/data"
